"""add_position_permissions

Revision ID: 07ba25e562a6
Revises: 70648886712d
Create Date: 2026-04-24 09:13:00.672789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ba25e562a6'
down_revision: Union[str, None] = '70648886712d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_permissions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_permissions')
    # ### end Alembic commands ###
