"""add_location_and_voice_fields

Revision ID: 15d7e43c1f16
Revises: e7bd3550e14d
Create Date: 2026-05-16 12:09:55.759695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d7e43c1f16'
down_revision: Union[str, None] = 'e7bd3550e14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overtimes', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('overtimes', sa.Column('voice_url', sa.String(), nullable=True))
    op.add_column('overtimes', sa.Column('voice_summary', sa.String(), nullable=True))
    op.add_column('overtimes', sa.Column('approved_hours', sa.Float(), nullable=True))
    op.alter_column('overtimes', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('projects', sa.Column('weekly_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'weekly_limit')
    op.alter_column('overtimes', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('overtimes', 'approved_hours')
    op.drop_column('overtimes', 'voice_summary')
    op.drop_column('overtimes', 'voice_url')
    op.drop_column('overtimes', 'location_name')
    # ### end Alembic commands ###
