"""setup_cascades

Revision ID: 25591f2c6282
Revises: 9eb498ce8d4d
Create Date: 2026-04-16 12:53:07.839339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25591f2c6282'
down_revision: Union[str, None] = '9eb498ce8d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_manager_id_fkey', 'departments', type_='foreignkey')
    op.drop_constraint('departments_parent_id_fkey', 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'departments', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('job_positions_parent_id_fkey', 'job_positions', type_='foreignkey')
    op.drop_constraint('job_positions_department_id_fkey', 'job_positions', type_='foreignkey')
    op.create_foreign_key(None, 'job_positions', 'job_positions', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_positions', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_position_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'job_positions', ['position_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('users_position_id_fkey', 'users', 'job_positions', ['position_id'], ['id'])
    op.drop_constraint(None, 'job_positions', type_='foreignkey')
    op.drop_constraint(None, 'job_positions', type_='foreignkey')
    op.create_foreign_key('job_positions_department_id_fkey', 'job_positions', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('job_positions_parent_id_fkey', 'job_positions', 'job_positions', ['parent_id'], ['id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_parent_id_fkey', 'departments', 'departments', ['parent_id'], ['id'])
    op.create_foreign_key('departments_manager_id_fkey', 'departments', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###
