"""add_project_dynamic_stages

Revision ID: 3979eba48486
Revises: 6e06801df81e
Create Date: 2026-04-10 12:13:18.139105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3979eba48486'
down_revision: Union[str, None] = '6e06801df81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'crm_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'stage_id')
    # ### end Alembic commands ###
