"""add dual approval fields and audit logs

Revision ID: 3fbf87b687b7
Revises: dd5ddafd87dd
Create Date: 2026-02-26 12:41:10.997909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbf87b687b7'
down_revision: Union[str, None] = 'dd5ddafd87dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
