"""setup_user_overtime_cascades

Revision ID: 4836db7f403d
Revises: 25591f2c6282
Create Date: 2026-04-16 13:03:12.085580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4836db7f403d'
down_revision: Union[str, None] = '25591f2c6282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('overtimes_user_id_fkey', 'overtimes', type_='foreignkey')
    op.drop_constraint('overtimes_project_id_fkey', 'overtimes', type_='foreignkey')
    op.create_foreign_key(None, 'overtimes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'overtimes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overtimes', type_='foreignkey')
    op.drop_constraint(None, 'overtimes', type_='foreignkey')
    op.create_foreign_key('overtimes_project_id_fkey', 'overtimes', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('overtimes_user_id_fkey', 'overtimes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
