"""Expand CRM and Projects finally

Revision ID: 7cab01f55378
Revises: 07ba25e562a6
Create Date: 2026-04-26 15:08:39.031166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cab01f55378'
down_revision: Union[str, None] = '07ba25e562a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('counterparties', sa.Column('kpp', sa.String(length=20), nullable=True))
    op.add_column('counterparties', sa.Column('ogrn', sa.String(length=20), nullable=True))
    op.add_column('counterparties', sa.Column('legal_address', sa.String(), nullable=True))
    op.add_column('counterparties', sa.Column('postal_address', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('gross_profit', sa.Float(), nullable=True))
    op.add_column('deals', sa.Column('net_profit', sa.Float(), nullable=True))
    op.add_column('deals', sa.Column('turnover', sa.Float(), nullable=True))
    op.add_column('deals', sa.Column('labor_cost', sa.Float(), nullable=True))
    op.alter_column('projects', 'budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'gross_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'net_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'labor_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'ntk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'aup',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'aup',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'ntk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'labor_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'turnover',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'net_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'gross_profit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('projects', 'budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('deals', 'labor_cost')
    op.drop_column('deals', 'turnover')
    op.drop_column('deals', 'net_profit')
    op.drop_column('deals', 'gross_profit')
    op.drop_column('counterparties', 'postal_address')
    op.drop_column('counterparties', 'legal_address')
    op.drop_column('counterparties', 'ogrn')
    op.drop_column('counterparties', 'kpp')
    op.drop_table('project_attachments')
    op.drop_table('deal_attachments')
    # ### end Alembic commands ###
