"""add granular overtime statuses

Revision ID: 81f5e8d6a988
Revises: 3fbf87b687b7
Create Date: 2026-02-27 06:02:53.727509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f5e8d6a988'
down_revision: Union[str, None] = '3fbf87b687b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
