"""setup_audit_crm_cascades

Revision ID: 9a340a78a6b3
Revises: ab3a4e94fc61
Create Date: 2026-04-16 14:00:36.562149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a340a78a6b3'
down_revision: Union[str, None] = 'ab3a4e94fc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('deals_assigned_id_fkey', 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'users', ['assigned_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('leads_assigned_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_assigned_id_fkey', 'leads', 'users', ['assigned_id'], ['id'])
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key('deals_assigned_id_fkey', 'deals', 'users', ['assigned_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
