"""add_custom_task_statuses_and_departments

Revision ID: 9a59ad5953bf
Revises: ecbd350cbc5b
Create Date: 2026-04-28 09:54:38.174918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a59ad5953bf'
down_revision: Union[str, None] = 'ecbd350cbc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tasks', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('status_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'TODO'::character varying"))
    op.create_foreign_key(None, 'tasks', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'task_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'TODO'::character varying"))
    op.drop_column('tasks', 'status_id')
    op.drop_column('tasks', 'department_id')
    op.drop_table('task_statuses')
    # ### end Alembic commands ###
