"""setup_project_manager_cascades

Revision ID: ab3a4e94fc61
Revises: 4836db7f403d
Create Date: 2026-04-16 13:32:35.730349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3a4e94fc61'
down_revision: Union[str, None] = '4836db7f403d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('projects_lead_engineer_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_manager_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_lead_programmer_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_gip_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['gip_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['lead_engineer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['lead_programmer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_gip_id_fkey', 'projects', 'users', ['gip_id'], ['id'])
    op.create_foreign_key('projects_lead_programmer_id_fkey', 'projects', 'users', ['lead_programmer_id'], ['id'])
    op.create_foreign_key('projects_manager_id_fkey', 'projects', 'users', ['manager_id'], ['id'])
    op.create_foreign_key('projects_lead_engineer_id_fkey', 'projects', 'users', ['lead_engineer_id'], ['id'])
    op.alter_column('projects', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
