"""Add OrgStructure and RBAC

Revision ID: c6ad332b8dfc
Revises: fbc03923a853
Create Date: 2026-04-10 09:50:03.557171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ad332b8dfc'
down_revision: Union[str, None] = 'fbc03923a853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.add_column('departments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_constraint('departments_head_id_fkey', 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'users', ['manager_id'], ['id'])
    op.drop_column('departments', 'head_id')
    op.alter_column('user_otps', 'type',
               existing_type=postgresql.ENUM('login', 'password_reset', name='otptype'),
               type_=sa.Enum('login', 'password_reset', name='otptype', native_enum=False),
               existing_nullable=False)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('employee', 'manager', 'head', 'admin', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'company',
               existing_type=postgresql.ENUM('Polymedia', 'AJ-techCom', name='usercompany'),
               type_=sa.Enum('Polymedia', 'AJ_techCom', name='usercompany', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Polymedia'::usercompany"))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'company',
               existing_type=sa.Enum('Polymedia', 'AJ_techCom', name='usercompany', native_enum=False),
               type_=postgresql.ENUM('Polymedia', 'AJ-techCom', name='usercompany'),
               existing_nullable=False,
               existing_server_default=sa.text("'Polymedia'::usercompany"))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('employee', 'manager', 'head', 'admin', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'role_id')
    op.alter_column('user_otps', 'type',
               existing_type=sa.Enum('login', 'password_reset', name='otptype', native_enum=False),
               type_=postgresql.ENUM('login', 'password_reset', name='otptype'),
               existing_nullable=False)
    op.add_column('departments', sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_head_id_fkey', 'departments', 'users', ['head_id'], ['id'])
    op.drop_column('departments', 'extra_data')
    op.drop_column('departments', 'manager_id')
    op.drop_column('departments', 'parent_id')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
