"""Add Task dates and CRM stages

Revision ID: c6ca76d41c88
Revises: c6ad332b8dfc
Create Date: 2026-04-10 09:56:22.187584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ca76d41c88'
down_revision: Union[str, None] = 'c6ad332b8dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deals', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deals', 'crm_stages', ['stage_id'], ['id'])
    op.add_column('leads', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'crm_stages', ['stage_id'], ['id'])
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_data')
    op.drop_column('tasks', 'start_date')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'stage_id')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'stage_id')
    op.drop_table('crm_stages')
    # ### end Alembic commands ###
