"""add_manager_to_counterparty

Revision ID: cb0462fd3485
Revises: c38ee13b45eb
Create Date: 2026-04-27 06:23:08.262896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0462fd3485'
down_revision: Union[str, None] = 'c38ee13b45eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparties', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'counterparties', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'counterparties', type_='foreignkey')
    op.drop_column('counterparties', 'manager_id')
    # ### end Alembic commands ###
