"""add dual approval fields and audit logs

Revision ID: dd5ddafd87dd
Revises: 458996723945
Create Date: 2026-02-26 12:09:08.784048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5ddafd87dd'
down_revision: Union[str, None] = '458996723945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('overtimes', sa.Column('manager_approved', sa.Boolean(), nullable=True))
    op.add_column('overtimes', sa.Column('head_approved', sa.Boolean(), nullable=True))
    op.add_column('overtimes', sa.Column('manager_comment', sa.String(), nullable=True))
    op.add_column('overtimes', sa.Column('head_comment', sa.String(), nullable=True))
    op.drop_constraint('projects_department_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('projects_department_id_fkey', 'projects', 'departments', ['department_id'], ['id'])
    op.drop_column('overtimes', 'head_comment')
    op.drop_column('overtimes', 'manager_comment')
    op.drop_column('overtimes', 'head_approved')
    op.drop_column('overtimes', 'manager_approved')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
