"""add_company_to_user

Revision ID: e7bd3550e14d
Revises: 3fda748f506b
Create Date: 2026-03-26 12:52:06.605017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bd3550e14d'
down_revision: Union[str, None] = '3fda748f506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем тип ENUM для PostgreSQL вручную
    user_company_enum = sa.Enum('Polymedia', 'AJ-techCom', name='usercompany')
    user_company_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('company', sa.Enum('Polymedia', 'AJ-techCom', name='usercompany'), nullable=False, server_default='Polymedia'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    # Удаляем тип ENUM
    sa.Enum(name='usercompany').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
