"""Add TaskType and dynamic types

Revision ID: f67b5634d782
Revises: d630b2a19db4
Create Date: 2026-04-27 12:12:49.112684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67b5634d782'
down_revision: Union[str, None] = 'd630b2a19db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tasks', sa.Column('type_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.create_foreign_key(None, 'tasks', 'task_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.drop_column('tasks', 'type_id')
    op.drop_table('task_types')
    # ### end Alembic commands ###
